In pre_scale call scaling_factory.get_original_value.
Otherwise we pre-register a scale for a field that is not there.
Sample error:

```
http://localhost:8080/Plone/@@ajax-search
Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 167, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 376, in publish_module
  Module ZPublisher.WSGIPublisher, line 271, in publish
  Module ZPublisher.mapply, line 85, in mapply
  Module ZPublisher.WSGIPublisher, line 68, in call_object
  Module Products.CMFPlone.browser.search, line 288, in __call__
  Module Products.CMFPlone.browser.search, line 303, in get_image_tag
  Module plone.memoize.volatile, line 74, in replacement
  Module plone.namedfile.scaling, line 601, in tag
  Module plone.namedfile.scaling, line 583, in tag
  Module plone.namedfile.scaling, line 539, in scale
  Module plone.namedfile.scaling, line 61, in __init__
AttributeError: 'RequestContainer' object has no attribute 'image'
```

This is what causes a test failure in this test:

```
$ bin/test --all -s Products.CMFPlone -m test_robot -t 'Simple Livesearch'
```